version: '3'
services:
  zoo:
    image: zookeeper
    container_name: zk
    restart: always
    hostname: zoo
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo
  kowl:
    image: quay.io/cloudhut/kowl
    restart: on-failure
    hostname: kowl
    container_name: kowl
    volumes:
    - ./kowl_config.yaml:/etc/kowl/config.yaml
    ports:
    - "8080:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    depends_on:
      - kafka
  rabbitmq:
    container_name: rmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672 # for RabbitMQ GUI
      - 5672:5672 # for sender and consumer connections
    # volumes:
    #   - ./db-data/rabbitmq/data/:/var/lib/rabbitmq
    #   - ./db-data/rabbitmq/log/:/var/log/rabbitmq
  eventsdb:
    image: 'mongo:4.2.17-bionic'
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: myevents
    # volumes:
    #   - ./db-data/mongo/:/data/db
  events:
    container_name: events
    build:
      context: .
      dockerfile: Dockerfile.eventservice
    ports:
      - 8181:8181
      - 9191:9191
    depends_on:
      - rabbitmq
      - eventsdb
      - kafka
    environment:
      - AMQP_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGO_URL=mongodb://events-db/events
      # Don't put quotes around like 'kafka:19092' or "kafka:19092"; GO's os.getnev will stringify it.
      - KAFKA_URL=kafka:19092
  booking:
    container_name: booking
    build:
      context: .
      dockerfile: Dockerfile.bookingservice
    ports:
      - 8182:8182
    depends_on:
      - rabbitmq
      - eventsdb
      - kafka
    environment:
      - AMQP_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - KAFKA_URL=kafka:19092