version: '3'
services:
  rabbitmq:
    container_name: rmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672 # for RabbitMQ GUI
      - 5672:5672 # for sender and consumer connections
    volumes:
      - ./db-data/rabbitmq/data/:/var/lib/rabbitmq
      - ./db-data/rabbitmq/log/:/var/log/rabbitmq
  eventsdb:
    image: 'mongo:4.2.17-bionic'
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: myevents
    volumes:
      - ./db-data/mongo/:/data/db
  events:
    container_name: events
    build:
      context: .
      dockerfile: Dockerfile.eventservice
    ports:
      - 8180:8180
      - 9191:9191
    depends_on:
      - rabbitmq
      - eventsdb
    environment:
      - AMQP_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGO_URL=mongodb://events-db/events